[metadata]
name = ShortURL
description = Library for running live trading and back testing.
author = Nicolas Piola Parucker
platforms = win32
classifiers =
    Programming Language :: Python :: 3.14
version = 0.0.0

[options]
packages =
    short_url
    short_url.repositories
    short_url.databases

package_dir =
    =src
zip_safe = no
install_requires =
    sqlalchemy
    setuptools
    wheel
    testcontainers
    psycopg2
    pytest

[options.package_data]
short_url = py.typed
short_url.repositories = py.typed
short_url.databases = py.typed
